source 'https://rubygems.org'

gem 'rails', '~> 4.0.0.beta1'
gem 'sqlite3'

# gem 'listen'
gem 'rb-inotify', :require => false  # linux
gem 'rb-fsevent', :require => false  # mac os x
gem 'rb-kqueue',  :require => false  # bsd
